<a href="https://colab.research.google.com/github/SamaSamrin/NLP-Bag-of-Words-Implementation-Attempt/blob/main/NLP_Ass_3_ROUGH.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
from collections import defaultdict, Counter
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from typing import List
#import re

In [2]:
ID = "1191609"
NAME = "Sama Samrin"

In [14]:
class CustomBagOfWords:
    
    def __init__(self, data: List[List[str]]):
        #data is a list of lists which consists of words. For example = [["it", "consist", "of", "words"]]
        self.data = data 
        #Map to store words to indexes in the vocab
        self.word_to_index = {}
        #Vocab stores all the unique words in the dataset.
        self.vocab = set()
    
    def _build_vocab(self):
        """Method to build vocabulary. Vocabulary is a list of unique words in the dataset and it is alphabetically sorted. 
        Hint: Use the self.vocab to store unique words
        Note: Include only words whose length is >= 2
        """
        ignore = ["a", "an", "the", "this", "that", "is", "it", "to", "and"] #ignoring the stop words
        punctuation = []
        words = data
        self.vocab = self.vocab
        #Implement your logic above this line
        #Do not modify the below line
        self.vocab = sorted(list(self.vocab))
    
    def create_index_map(self):
        """Method to map every word to its index in the vocabulary
        Hint: Iterate over the vocabulary and store them in word_to_index
        """
        #Implement the logic below this line
    
    def bow(self, input_sent: List[str]) -> np.ndarray:
        """Method which accepts input_sent of the form : ["is", "this", "a", "sent"].
        Task:
            Implement the bag of words approach for the above input. 
            This function should return a vector of counts for the given inputs.
            The output shape of the vector should be 1 x len(self.vocab)
            The output should be a numpy array
            Example:
                length of vocabulary = 10
                input_sent = ["is", "this", "a", "sent"]
                The method should return a vector of shape 1 x 10.
        """
        pass
    
    def create_vector(self) -> np.ndarray:
        """Method iterates over the whole dataset and creates the bag of words vector of shape:  len(self.data) x len(self.vocab)"""
        #Do not modify this function
        self._build_vocab()
        self.create_index_map()
        vector = []
        for sent in self.data:
            sent_vector = self.bow(sent)
            vector.append(sent_vector)
        vector = np.array(vector)
        return vector

In [10]:
data = "   This is a message to be cleaned. It might involve some things like: <br>, ?, :, ''  adjacent spaces, and tabs     . "
vocab = re.sub("[^\w]", " ",  data).split()

print(vocab)
print(type(vocab))

['This', 'is', 'a', 'message', 'to', 'be', 'cleaned', 'It', 'might', 'involve', 'some', 'things', 'like', 'br', 'adjacent', 'spaces', 'and', 'tabs']
<class 'list'>


#**My Attempts**

##Creating Vocab

In [34]:
corpus = ["this is a document", "this is a processed document", "is this a document", "this is not a document"]
words = set()

for i in range(len(corpus)):
  x = corpus[i].split(" ")
  for j in range(len(x)):
    if x[j] not in words:
      words.add(x[j])

print(words)

{'this', 'not', 'is', 'processed', 'document', 'a'}


## Create index map

In [70]:
"""Method to map every word to its index in the vocabulary
        Hint: Iterate over the vocabulary and store them in word_to_index
        """
#word_to_index = dict.fromkeys(words) #empty dictionary
word_to_index = dict.fromkeys(words)
count = 0

for i in words:
  word_to_index[i] = count
  count +=1
  #print(i, count-1)

"""for word in words:
  #print(word)
  count = 0
  for i in range(len(corpus)):
      if word in corpus[i]:
       count+=1
  print(word, " : ", count)
  word_to_index[word] = count
"""
print(word_to_index)

{'this': 0, 'not': 1, 'is': 2, 'processed': 3, 'document': 4, 'a': 5}


##Vectorization

In [108]:
#def bow(self, input_sent: List[str]) -> np.ndarray:
"""Method which accepts input_sent of the form : ["is", "this", "a", "sent"].
        Task:
            Implement the bag of words approach for the above input. 
            This function should return a vector of counts for the given inputs.
            The output shape of the vector should be 1 x len(self.vocab)
            The output should be a numpy array
            Example:
                length of vocabulary = 10
                input_sent = ["is", "this", "a", "sent"]
                The method should return a vector of shape 1 x 10.
pass"""


vector_shape = (1, len(words))
vector = np.zeros(vector_shape, dtype=int)
print(vector)

input_sent = np.array(["is", "this", "a", "sent"])

for i in input_sent:
  if i not in words:
    input_index = np.where(input_sent == i)
    print("OOV error with the word: ", i, " at ", input_index[0])
  elif i in word_to_index:
    input_index = np.where(input_sent == i)
    indx = word_to_index[i]
    #print(vector[0][indx])
    vector[0][indx] += 1

"""for i in word_to_index:
  if i not in words:
    print("OOV error")
  elif i in input_sent:
    indx = word_to_index[i]
    #print(vector[0][indx])
    vector[0][indx] += 1"""
  #print(i, word_to_index[i], indx)
print(words)
print(vector)

[[0 0 0 0 0 0]]
OOV error with the word:  sent  at  [3]
{'this', 'not', 'is', 'processed', 'document', 'a'}
[[1 0 1 0 0 1]]


## Final method/work



---



#Others

In [22]:
original_corpus = ["this is a document", "this is a processed document", "is this a document", "this is not a document"]
x = CountVectorizer().fit_transform(original_corpus)
print(x)

sklearn_output = x.toarray()

print(sklearn_output)

  (0, 4)	1
  (0, 1)	1
  (0, 0)	1
  (1, 4)	1
  (1, 1)	1
  (1, 0)	1
  (1, 3)	1
  (2, 4)	1
  (2, 1)	1
  (2, 0)	1
  (3, 4)	1
  (3, 1)	1
  (3, 0)	1
  (3, 2)	1
[[1 1 0 0 1]
 [1 1 0 1 1]
 [1 1 0 0 1]
 [1 1 1 0 1]]


#**Testing**

In [15]:
#Do not modify code below this. If this modified you will be given straight away 0.
class testApproach:
    def __init__(self):
        self.original_corpus = ["this is a document", "this is a processed document", "is this a document", "This is not a document"]
        self.corpus = self.process(self.original_corpus)
        self.sklearn_bow = CountVectorizer()
        self.custom_bow = CustomBagOfWords(self.corpus)

    def process(self, corpus):
        corpus = [x.lower() for x in corpus]
        return [x.split() for x in corpus]
    
    def testBOW(self):
        sklearn_output = self.sklearn_bow.fit_transform(self.original_corpus).toarray()
        custom_output = self.custom_bow.create_vector()
        
        try:
            is_correct = np.allclose(sklearn_output, custom_output) 
        except:
            is_correct = False
        if is_correct is True:
            print(f"ID : {ID} | Name : {NAME} | ALL test cases passed.")
            print("===="*20)
        else:
            print(f"ID : {ID} | Name : {NAME} | ALL test cases Failed.")
            print("===="*20)
    
if __name__ == "__main__":
    tester = testApproach()
    tester.testBOW()

ID : 1191609 | Name : Sama Samrin | ALL test cases Failed.
